language: java
jdk:
 - oraclejdk8
script:
 - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
 - mvn -e -B clean compile
 - sonar-scanner -X -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_LOGIN
 - mvn -e sonar:sonar -Dsonar.login=$SONAR_LOGIN -Dsonar.host.url=https:/sonarqube.com
 - mvn -e -B package
