language: java
jdk:
 - oraclejdk8
 addons:
  sonarqube: true
script:
 - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
 - mvn -e -B clean compile
 - mvn -e sonar:sonar -Dsonar.login=$SONAR_LOGIN -Dsonar.host.url=https:/sonarqube.com
 - mvn -e -B package
